# Generated by Django 5.0.7 on 2024-11-25 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_shippingaddress_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'verbose_name_plural': 'Shipping Address'},
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='shipping_user',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='shipping_old_cart',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='shipping_phone',
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_address2',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
