# Generated by Django 5.0.7 on 2024-12-02 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='shipping_address2',
        ),
    ]
